[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Ligand2SMILES"
version = "0.1.0"
description = "A tool for converting ligand names to SMILES notation"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "Pedro Augusto Durao Rodrigues", email = "pedroaugustoduraorodrigues@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/KevlishviliGroup/Ligand2SMILES"
Issues = "https://github.com/KevlishviliGroup/Ligand2SMILES/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["Ligand2SMILES*"]

[tool.setuptools.package-data]
Ligand2SMILES = ["ligand_list.json"]
